### ISSUE TITLE
How to select a graph substitutions rule in TASO？

### ISSUE THREAD

**Issue by weiyu-Liu** [Experiment-code/OCGGS#1]
I am very interested in your work. It is written in the paper that you have used 157 graph  substitutions in TASO. Do you have detailed documents on these graph substitutions.

Thank you very much !

**Comment by Experiment-code** [comment]
Hi, we have no detailed documents on these graph substitutions.

We directly use (1) the graph substitution rules loaded from graph_subst.pb using the method "load_graph_xfer_from_pb_file", and (2) the rules written in the substitution.cc.

157 is obtained by counting the number of all rules.

**Comment by weiyu-Liu** [comment]
Thank you for your reply, but I noticed that TASO now has about 700 graph substitution  rules, so I don't quite understand how this 157 came out. Do you use the previous version of TASO?
When I read your code, I didn't find the interface you call these rules. Can you explain it a little. Can these interfaces be invoked in Python?
Thank you ！

**Comment by Experiment-code** [comment]
Hi, 
(1) We use the previously code of TASO.
(2) You can check this link to see how to load the rules.
https://github.com/Experiment-code/OCGGS/blob/master/src/core/ops.cc#L1134-L1174.
The loading method is the same as in TASO.
(3) The loading method cannot be invoked in python.

**Comment by weiyu-Liu** [comment]
Thank you very much. That's very helpful！
